### ISSUE TITLE
[1.12.2] Crash when attempting to lock a block

### ISSUE THREAD

**Issue by Lucky-Red** [Melonslise/Locks#39]
After updating to version 2.4 of the mod, the game is crashing with this error any time I attempt to place a lock:
```Description: Unexpected error

java.lang.IllegalAccessError: tried to access method net.minecraft.world.World.func_175663_a(IIIIIIZ)Z from class melonslise.locks.common.util.Cuboid6i
    at melonslise.locks.common.util.Cuboid6i.loaded(Cuboid6i.java:126)
    at melonslise.locks.client.event.LocksClientEvents.lambda$onClientTick$0(LocksClientEvents.java:56)
    at java.lang.Iterable.forEach(Unknown Source)
    at melonslise.locks.client.event.LocksClientEvents.onClientTick(LocksClientEvents.java:54)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1119_LocksClientEvents_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1708)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by MercurialPony** [comment]
Should be fixed now.
